# config/migrate/wp3_import.yaml
parameters:
  app.csv_import_file: "data/import/conversion_services.csv"
  app.csv_import_file_has_header: false
  app.csv_import_file_process_from_row: 8
  app.csv_import_file_multival_separator: ' ; '
  app.csv_import_file_structure:
    "Id":
      name: "id"
      type: "identifier"
    "Title":
      name: "title"
      column: 3
      necessary: true
      type: "string"
    "Accesspoints":
      name: "url"
      column: 5
      type: "url"
    "Description":
      name: "description"
      column: 6
      type: "string"
    "Communities":
      name: "community"
      column: 7
      type: "vocabulary"
    "Invocations":
      name: "invocation"
      column: 8
      type: "vocabulary"
  app.csv_export_file: "data/convert/conversions.csv"
  app.csv_vocab_formats_file: "data/import/formats_list.csv"
  app.csv_vocab_formats_file_has_header: false
  app.csv_vocab_formats_file_process_from_row: 8
  app.csv_vocab_formats_file_multival_separator: ' ; '
  app.csv_vocab_formats_file_structure:
    1:
      name: "mime-type"
    2:
      name: "title"
      necessary: true
