# config/migrate/wp3_import.yaml
parameters:
  app.csv_import_file: "data/import/conversion_services.csv"
  app.csv_import_file_has_header: false
  app.csv_import_file_process_from_row: 8
  app.csv_import_file_multival_separator: ' ; '
  app.csv_import_file_structure:
    "Id":
      type: "identifier"
      ignoreImport: true
    "Title":
      column: 3
      type: "string"
      necessary: true
    "Accesspoints":
      column: 5
      type: "url"
    "Description":
      column: 6
      type: "string"
    "Communities":
      column: 7
      type: "vocabulary"
    "Invocations":
      column: 8
      type: "vocabulary"
    "inputFormat":
      column: 13
      type: "vocabulary"
      "externalVocabulary": "formats"
      # make sure that the key is in line with the setting in the vocbulary
      "externalVocabularyKey": "Mime-type"
    "inputFormatComment":
      column: 14
      type: "string"
    "outputFormat":
      column: 15
      type: "vocabulary"
      "externalVocabulary": "formats"
      # make sure that the key is in line with the setting in the vocbulary
      "externalVocabularyKey": "Mime-type"
    "outputFormatComment":
      column: 16
      type: "string"
    "Statuses":
      column: 17
      type: "vocabulary"
  app.csv_export_file: "data/convert/services.csv"
  # vocabulary invocations settings
  app.csv_vocab_invocations_process_from_row: 0
  app.csv_vocab_invocations_multival_separator: ' ; '
  app.csv_vocab_invocations_structure:
    "Id":
      type: "identifier"
      ignoreImport: true
    "Name":
      column: 0
      type: "string"
      necessary: true
  app.csv_vocab_invocations_export_file: "data/convert/invocations.csv"
  # vocabulary communities settings
  app.csv_vocab_communities_process_from_row: 0
  app.csv_vocab_communities_multival_separator: ' ; '
  app.csv_vocab_communities_structure:
    "Id":
      type: "identifier"
      ignoreImport: true
    "Name":
      column: 0
      type: "string"
      necessary: true
  app.csv_vocab_communities_export_file: "data/convert/communities.csv"
  # vocabulary statuses settings
  app.csv_vocab_statuses_process_from_row: 0
  app.csv_vocab_statuses_multival_separator: ' ; '
  app.csv_vocab_statuses_structure:
    "Id":
      type: "identifier"
      ignoreImport: true
    "Name":
      column: 0
      type: "string"
      necessary: true
  app.csv_vocab_statuses_export_file: "data/convert/statuses.csv"
  # vocabulary formats settings
  app.csv_vocab_formats_file: "data/import/formats_list.csv"
  app.csv_vocab_formats_file_has_header: false
  app.csv_vocab_formats_file_process_from_row: 8
  app.csv_vocab_formats_file_multival_separator: ' ; '
  app.csv_vocab_formats_file_structure:
    "Id":
      type: "identifier"
      ignoreImport: true
    "Name":
      column: 2
      skipEmpty: true
      type: "string"
    "Mime-type":
      column: 1
      type: "string"
  app.csv_vocab_formats_file_export_file: "data/convert/formats.csv"
