# config/migrate/wp3_import.yaml
parameters:
  app.csv_import_file: "data/import/conversion_services.csv"
  app.csv_import_file_has_header: false
  app.csv_import_file_process_from_row: 8
  app.csv_import_file_multival_separator: ' ; '
  app.csv_import_file_structure:
    "Id":
      type: "identifier"
      ignoreImport: true
    "Title":
      column: 3
      type: "string"
      necessary: true
    "Accesspoints":
      column: 5
      type: "url"
    "Description":
      column: 6
      type: "string"
    "Communities":
      column: 7
      type: "vocabulary"
    "Invocations":
      column: 8
      type: "vocabulary"
  app.csv_export_file: "data/convert/conversions.csv"
  # vocabulary invocations settings
  app.csv_vocab_invocations_process_from_row: 0
  app.csv_vocab_invocations_multival_separator: ' ; '
  app.csv_vocab_invocations_structure:
    "Id":
      type: "identifier"
      ignoreImport: true
    "Name":
      column: 0
      type: "string"
      necessary: true
  app.csv_vocab_invocations_export_file: "data/convert/invo.csv"
  # vocabulary communities settings
  app.csv_vocab_communities_process_from_row: 0
  app.csv_vocab_communities_multival_separator: ' ; '
  app.csv_vocab_communities_structure:
    "Id":
      type: "identifier"
      ignoreImport: true
    "Name":
      column: 0
      type: "string"
      necessary: true
  app.csv_vocab_communities_export_file: "data/convert/comm.csv"
  # vocabulary formats settings
  app.csv_vocab_formats_file: "data/import/formats_list.csv"
  app.csv_vocab_formats_file_has_header: false
  app.csv_vocab_formats_file_process_from_row: 8
  app.csv_vocab_formats_file_multival_separator: ' ; '
  app.csv_vocab_formats_file_structure:
    1:
      name: "mime-type"
    2:
      name: "title"
      necessary: true
